#!/bin/sh /etc/rc.common

START=99
STOP=1
USE_PROCD=1
PROG=/usr/share/script/watchdog.py
LOG_FILE=/var/log/watchdog.log
start_watchdog() {
	# set core file size
	ulimit -c unlimited

	#python3 $PROG 2>&1 | tee "$LOG_FILE" &
	python3 $PROG &
}

stop_watchdog() {
	watchdog=`ps -w | grep -w watchdog | grep -v grep | awk '{print $1}'`
	[ -n "$watchdog" ] && {
	    for pid in "$watchdog"
        do
            kill -9 $pid
        done
    }
}

start_service() {
	sleep 12
	start_watchdog
}

stop_service() {
	stop_watchdog
}

reload_service() {
	stop_watchdog
	sleep 1
	start_watchdog
}

