#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=55
STOP=1
DEPEND=fstab
USE_PROCD=1
PROG=/usr/share/klippy-env/bin/python
USERDATA=/mnt/UDISK/
PRINTER_CONFIG_DIR=$USERDATA/printer_config
PRINTER_LOGS_DIR=$USERDATA/printer_logs
PRINTER_CUSTOM_CFG=$PRINTER_CONFIG_DIR/printer.cfg
PRINTER_DEFAULT_CFG=/usr/share/klipper-brain/printer_config/printer.cfg
VIRTUAL_SD=/root/gcode_files
REAL_SD=$USERDATA/.crealityprint/upload
OOM_ADJ=-17

start_service() {

    [ -d $PRINTER_CONFIG_DIR ] || mkdir -p $PRINTER_CONFIG_DIR
    [ -s $PRINTER_CUSTOM_CFG ] || cp $PRINTER_DEFAULT_CFG $PRINTER_CUSTOM_CFG

    [ -d $PRINTER_LOGS_DIR ] || mkdir -p $PRINTER_LOGS_DIR

    [ -L $VIRTUAL_SD ] || ln -s $REAL_SD $VIRTUAL_SD

    procd_open_instance
    procd_set_param env HOME=/root
    procd_set_param oom_adj $OOM_ADJ
    procd_set_param command $PROG /usr/share/klipper/klippy/klippy.py $PRINTER_CUSTOM_CFG -l $PRINTER_LOGS_DIR/klippy.log -a /tmp/klippy_uds
    procd_close_instance
}
