
/* DO NOT EDIT! This is an autogenerated file. See scripts/buildcommands.py. */

#include "board/irq.h"
#include "board/pgm.h"
#include "command.h"
#include "compiler.h"
#include "initial_pins.h"

void
ctr_run_initfuncs(void)
{
    extern void alloc_init(void);
    alloc_init();
    extern void initial_pins_setup(void);
    initial_pins_setup();
    extern void prescaler_init(void);
    prescaler_init();
    extern void timer_init(void);
    timer_init();
    extern void watchdog_init(void);
    watchdog_init();
    extern void serial_init(void);
    serial_init();
}

void
ctr_run_shutdownfuncs(void)
{
    extern void sendf_shutdown(void);
    sendf_shutdown();
    extern void move_reset(void);
    move_reset();
    extern void digital_out_shutdown(void);
    digital_out_shutdown();
    extern void stepper_shutdown(void);
    stepper_shutdown();
    extern void trsync_shutdown(void);
    trsync_shutdown();
    extern void analog_in_shutdown(void);
    analog_in_shutdown();
    extern void spidev_shutdown(void);
    spidev_shutdown();
    extern void pwm_shutdown(void);
    pwm_shutdown();
    extern void st7920_shutdown(void);
    st7920_shutdown();
    extern void hd44780_shutdown(void);
    hd44780_shutdown();
    extern void tmcuart_shutdown(void);
    tmcuart_shutdown();
    extern void timer_reset(void);
    timer_reset();
}

void
ctr_run_taskfuncs(void)
{
    irq_poll();
    extern void trsync_task(void);
    trsync_task();
    irq_poll();
    extern void analog_in_task(void);
    analog_in_task();
    irq_poll();
    extern void thermocouple_task(void);
    thermocouple_task();
    irq_poll();
    extern void adxl345_task(void);
    adxl345_task();
    irq_poll();
    extern void spi_angle_task(void);
    spi_angle_task();
    irq_poll();
    extern void mpu9250_task(void);
    mpu9250_task();
    irq_poll();
    extern void buttons_task(void);
    buttons_task();
    irq_poll();
    extern void tmcuart_task(void);
    tmcuart_task();
    irq_poll();
    extern void counter_task(void);
    counter_task();
    irq_poll();
    extern void watchdog_reset(void);
    watchdog_reset();
    irq_poll();
    extern void console_task(void);
    console_task();
    irq_poll();
    extern void t5uid1_task(void);
    t5uid1_task();
    irq_poll();
}

uint8_t __always_inline
ctr_lookup_static_string(const char *str)
{
    if (__builtin_strcmp(str, "Shutdown cleared when not shutdown") == 0)
        return 2;
    if (__builtin_strcmp(str, "Timer too close") == 0)
        return 3;
    if (__builtin_strcmp(str, "sentinel timer called") == 0)
        return 4;
    if (__builtin_strcmp(str, "Invalid command") == 0)
        return 5;
    if (__builtin_strcmp(str, "Message encode error") == 0)
        return 6;
    if (__builtin_strcmp(str, "Command parser error") == 0)
        return 7;
    if (__builtin_strcmp(str, "Command request") == 0)
        return 8;
    if (__builtin_strcmp(str, "config_reset only available when shutdown") == 0)
        return 9;
    if (__builtin_strcmp(str, "oids already allocated") == 0)
        return 10;
    if (__builtin_strcmp(str, "Can't assign oid") == 0)
        return 11;
    if (__builtin_strcmp(str, "Invalid oid type") == 0)
        return 12;
    if (__builtin_strcmp(str, "Already finalized") == 0)
        return 13;
    if (__builtin_strcmp(str, "Invalid move request size") == 0)
        return 14;
    if (__builtin_strcmp(str, "Move queue overflow") == 0)
        return 15;
    if (__builtin_strcmp(str, "alloc_chunks failed") == 0)
        return 16;
    if (__builtin_strcmp(str, "alloc_chunk failed") == 0)
        return 17;
    if (__builtin_strcmp(str, "update_digital_out not valid with active queue") == 0)
        return 18;
    if (__builtin_strcmp(str, "Scheduled digital out event will exceed max_duration") == 0)
        return 19;
    if (__builtin_strcmp(str, "Can not set soft pwm cycle ticks while updates pending") == 0)
        return 20;
    if (__builtin_strcmp(str, "Missed scheduling of next digital out event") == 0)
        return 21;
    if (__builtin_strcmp(str, "Can't reset time when stepper active") == 0)
        return 22;
    if (__builtin_strcmp(str, "Invalid count parameter") == 0)
        return 23;
    if (__builtin_strcmp(str, "Stepper too far in past") == 0)
        return 24;
    if (__builtin_strcmp(str, "Can't add signal that is already active") == 0)
        return 25;
    if (__builtin_strcmp(str, "ADC out of range") == 0)
        return 26;
    if (__builtin_strcmp(str, "Invalid spi config") == 0)
        return 27;
    if (__builtin_strcmp(str, "Thermocouple reader fault") == 0)
        return 28;
    if (__builtin_strcmp(str, "Thermocouple ADC out of range") == 0)
        return 29;
    if (__builtin_strcmp(str, "Invalid thermocouple chip type") == 0)
        return 30;
    if (__builtin_strcmp(str, "i2c_modify_bits: Odd number of bits!") == 0)
        return 31;
    if (__builtin_strcmp(str, "Scheduled pwm event will exceed max_duration") == 0)
        return 32;
    if (__builtin_strcmp(str, "Missed scheduling of next hard pwm event") == 0)
        return 33;
    if (__builtin_strcmp(str, "angle sensor requires cs pin") == 0)
        return 34;
    if (__builtin_strcmp(str, "Invalid spi_angle chip type") == 0)
        return 35;
    if (__builtin_strcmp(str, "Invalid buttons retransmit count") == 0)
        return 36;
    if (__builtin_strcmp(str, "Set button past maximum button count") == 0)
        return 37;
    if (__builtin_strcmp(str, "Max of 8 buttons") == 0)
        return 38;
    if (__builtin_strcmp(str, "tmcuart data too large") == 0)
        return 39;
    if (__builtin_strcmp(str, "Invalid neopixel update command") == 0)
        return 40;
    if (__builtin_strcmp(str, "Invalid neopixel data_size") == 0)
        return 41;
    if (__builtin_strcmp(str, "Rescheduled timer in the past") == 0)
        return 42;
    if (__builtin_strcmp(str, "Not a valid input pin") == 0)
        return 43;
    if (__builtin_strcmp(str, "Not an output pin") == 0)
        return 44;
    if (__builtin_strcmp(str, "Not a valid ADC pin") == 0)
        return 45;
    if (__builtin_strcmp(str, "Invalid spi_setup parameters") == 0)
        return 46;
    if (__builtin_strcmp(str, "Failed to send i2c start") == 0)
        return 47;
    if (__builtin_strcmp(str, "i2c timeout") == 0)
        return 48;
    if (__builtin_strcmp(str, "Unsupported i2c bus") == 0)
        return 49;
    if (__builtin_strcmp(str, "PWM already programmed at different speed") == 0)
        return 50;
    if (__builtin_strcmp(str, "Can not use timer1 for PWM; timer1 is used for timers") == 0)
        return 51;
    if (__builtin_strcmp(str, "Not a valid PWM pin") == 0)
        return 52;
    if (__builtin_strcmp(str, "Watchdog timer!") == 0)
        return 53;
    return 0xff;
}

const struct initial_pin_s initial_pins[] PROGMEM = {
};
const int initial_pins_size PROGMEM = ARRAY_SIZE(initial_pins);

static const uint8_t command_parameters0[] PROGMEM = {
    PT_uint16 };
static const uint8_t command_parameters1[] PROGMEM = {
    PT_uint32, PT_uint16 };
static const uint8_t command_parameters2[] PROGMEM = {
    PT_uint32, PT_progmem_buffer };
static const uint8_t command_parameters3[] PROGMEM = {
    PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters4[] PROGMEM = {
    PT_uint32, PT_uint32 };
static const uint8_t command_parameters5[] PROGMEM = {
    PT_uint32 };
static const uint8_t command_parameters6[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte, PT_uint16 };
static const uint8_t command_parameters7[] PROGMEM = {
    PT_buffer };
static const uint8_t command_parameters8[] PROGMEM = {
    PT_byte, PT_int32 };
static const uint8_t command_parameters9[] PROGMEM = {
    PT_byte, PT_byte, PT_uint32, PT_byte };
static const uint8_t command_parameters10[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters11[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16 };
static const uint8_t command_parameters12[] PROGMEM = {
    PT_byte, PT_buffer };
static const uint8_t command_parameters13[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte };
static const uint8_t command_parameters14[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint16, PT_byte, PT_byte, PT_uint16 };
static const uint8_t command_parameters15[] PROGMEM = {
    PT_byte, PT_uint16, PT_buffer };
static const uint8_t command_parameters16[] PROGMEM = {
    PT_byte, PT_uint32, PT_buffer };
static const uint8_t command_parameters17[] PROGMEM = {
    PT_byte, PT_uint16 };
static const uint8_t command_parameters18[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint16, PT_byte, PT_uint32, PT_uint16 };
static const uint8_t command_parameters19[] PROGMEM = {
    PT_byte, PT_byte, PT_buffer };
static const uint8_t command_parameters20[] PROGMEM = {
    PT_byte, PT_byte };
static const uint8_t command_parameters21[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters22[] PROGMEM = {
    PT_uint32, PT_byte };
static const uint8_t command_parameters23[] PROGMEM = {
    PT_byte };
static const uint8_t command_parameters24[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32 };
static const uint8_t command_parameters25[] PROGMEM = {
    PT_byte, PT_uint32 };
static const uint8_t command_parameters26[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters27[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16, PT_int16 };
static const uint8_t command_parameters28[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters29[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_uint32, PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters30[] PROGMEM = {
    PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters31[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_uint32, PT_uint16, PT_uint16, PT_byte };
static const uint8_t command_parameters32[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte };
static const uint8_t command_parameters33[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters34[] PROGMEM = {
    PT_byte, PT_buffer, PT_buffer };
static const uint8_t command_parameters35[] PROGMEM = {
    PT_byte, PT_buffer, PT_uint32 };
static const uint8_t command_parameters36[] PROGMEM = {
    PT_uint32, PT_uint32, PT_uint16 };
static const uint8_t command_parameters37[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint16, PT_uint16, PT_uint32 };
static const uint8_t command_parameters38[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters39[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters40[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_byte };
static const uint8_t command_parameters41[] PROGMEM = {
    PT_byte, PT_buffer, PT_byte };
static const uint8_t command_parameters42[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte, PT_uint32, PT_uint32 };
static const uint8_t command_parameters43[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16, PT_uint32, PT_uint32 };
static const uint8_t command_parameters44[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16, PT_byte, PT_buffer };

const struct command_encoder command_encoder_79 PROGMEM = {    
    // starting
    .msg_id=79,
    .num_params=0,
    .param_types = 0,
    .max_size=6,
};
const struct command_encoder command_encoder_80 PROGMEM = {    
    // is_shutdown static_string_id=%hu
    .msg_id=80,
    .num_params=1,
    .param_types = command_parameters0,
    .max_size=9,
};
const struct command_encoder command_encoder_81 PROGMEM = {    
    // shutdown clock=%u static_string_id=%hu
    .msg_id=81,
    .num_params=2,
    .param_types = command_parameters1,
    .max_size=14,
};
const struct command_encoder command_encoder_0 PROGMEM = {    
    // identify_response offset=%u data=%.*s
    .msg_id=0,
    .num_params=2,
    .param_types = command_parameters2,
    .max_size=64,
};
const struct command_encoder command_encoder_82 PROGMEM = {    
    // stats count=%u sum=%u sumsq=%u
    .msg_id=82,
    .num_params=3,
    .param_types = command_parameters3,
    .max_size=21,
};
const struct command_encoder command_encoder_83 PROGMEM = {    
    // uptime high=%u clock=%u
    .msg_id=83,
    .num_params=2,
    .param_types = command_parameters4,
    .max_size=16,
};
const struct command_encoder command_encoder_84 PROGMEM = {    
    // clock clock=%u
    .msg_id=84,
    .num_params=1,
    .param_types = command_parameters5,
    .max_size=11,
};
const struct command_encoder command_encoder_85 PROGMEM = {    
    // config is_config=%c crc=%u is_shutdown=%c move_count=%hu
    .msg_id=85,
    .num_params=4,
    .param_types = command_parameters6,
    .max_size=18,
};
const struct command_encoder command_encoder_86 PROGMEM = {    
    // pong data=%*s
    .msg_id=86,
    .num_params=1,
    .param_types = command_parameters7,
    .max_size=64,
};
const struct command_encoder command_encoder_87 PROGMEM = {    
    // debug_result val=%u
    .msg_id=87,
    .num_params=1,
    .param_types = command_parameters5,
    .max_size=11,
};
const struct command_encoder command_encoder_88 PROGMEM = {    
    // stepper_position oid=%c pos=%i
    .msg_id=88,
    .num_params=2,
    .param_types = command_parameters8,
    .max_size=13,
};
const struct command_encoder command_encoder_89 PROGMEM = {    
    // endstop_state oid=%c homing=%c next_clock=%u pin_value=%c
    .msg_id=89,
    .num_params=4,
    .param_types = command_parameters9,
    .max_size=17,
};
const struct command_encoder command_encoder_90 PROGMEM = {    
    // trsync_state oid=%c can_trigger=%c trigger_reason=%c clock=%u
    .msg_id=90,
    .num_params=4,
    .param_types = command_parameters10,
    .max_size=17,
};
const struct command_encoder command_encoder_91 PROGMEM = {    
    // analog_in_state oid=%c next_clock=%u value=%hu
    .msg_id=91,
    .num_params=3,
    .param_types = command_parameters11,
    .max_size=16,
};
const struct command_encoder command_encoder_92 PROGMEM = {    
    // spi_transfer_response oid=%c response=%*s
    .msg_id=92,
    .num_params=2,
    .param_types = command_parameters12,
    .max_size=64,
};
const struct command_encoder command_encoder_93 PROGMEM = {    
    // thermocouple_result oid=%c next_clock=%u value=%u fault=%c
    .msg_id=93,
    .num_params=4,
    .param_types = command_parameters13,
    .max_size=20,
};
const struct command_encoder command_encoder_94 PROGMEM = {    
    // i2c_read_response oid=%c response=%*s
    .msg_id=94,
    .num_params=2,
    .param_types = command_parameters12,
    .max_size=64,
};
const struct command_encoder command_encoder_95 PROGMEM = {    
    // adxl345_status oid=%c clock=%u query_ticks=%u next_sequence=%hu buffered=%c fifo=%c limit_count=%hu
    .msg_id=95,
    .num_params=7,
    .param_types = command_parameters14,
    .max_size=28,
};
const struct command_encoder command_encoder_96 PROGMEM = {    
    // adxl345_data oid=%c sequence=%hu data=%*s
    .msg_id=96,
    .num_params=3,
    .param_types = command_parameters15,
    .max_size=64,
};
const struct command_encoder command_encoder_97 PROGMEM = {    
    // spi_angle_transfer_response oid=%c clock=%u response=%*s
    .msg_id=97,
    .num_params=3,
    .param_types = command_parameters16,
    .max_size=64,
};
const struct command_encoder command_encoder_98 PROGMEM = {    
    // spi_angle_end oid=%c sequence=%hu
    .msg_id=98,
    .num_params=2,
    .param_types = command_parameters17,
    .max_size=11,
};
const struct command_encoder command_encoder_99 PROGMEM = {    
    // spi_angle_data oid=%c sequence=%hu data=%*s
    .msg_id=99,
    .num_params=3,
    .param_types = command_parameters15,
    .max_size=64,
};
const struct command_encoder command_encoder_100 PROGMEM = {    
    // mpu9250_status oid=%c clock=%u query_ticks=%u next_sequence=%hu buffered=%c fifo=%u limit_count=%hu
    .msg_id=100,
    .num_params=7,
    .param_types = command_parameters18,
    .max_size=31,
};
const struct command_encoder command_encoder_101 PROGMEM = {    
    // mpu9250_data oid=%c sequence=%hu data=%*s
    .msg_id=101,
    .num_params=3,
    .param_types = command_parameters15,
    .max_size=64,
};
const struct command_encoder command_encoder_102 PROGMEM = {    
    // buttons_state oid=%c ack_count=%c state=%*s
    .msg_id=102,
    .num_params=3,
    .param_types = command_parameters19,
    .max_size=64,
};
const struct command_encoder command_encoder_103 PROGMEM = {    
    // tmcuart_response oid=%c read=%*s
    .msg_id=103,
    .num_params=2,
    .param_types = command_parameters12,
    .max_size=64,
};
const struct command_encoder command_encoder_104 PROGMEM = {    
    // neopixel_result oid=%c success=%c
    .msg_id=104,
    .num_params=2,
    .param_types = command_parameters20,
    .max_size=10,
};
const struct command_encoder command_encoder_105 PROGMEM = {    
    // counter_state oid=%c next_clock=%u count=%u count_clock=%u
    .msg_id=105,
    .num_params=4,
    .param_types = command_parameters21,
    .max_size=23,
};
const struct command_encoder command_encoder_106 PROGMEM = {    
    // t5uid1_received command=%c data=%*s
    .msg_id=106,
    .num_params=2,
    .param_types = command_parameters12,
    .max_size=64,
};

const __always_inline struct command_encoder *
ctr_lookup_encoder(const char *str)
{
    if (__builtin_strcmp(str, "starting") == 0)
        return &command_encoder_79;
    if (__builtin_strcmp(str, "is_shutdown static_string_id=%hu") == 0)
        return &command_encoder_80;
    if (__builtin_strcmp(str, "shutdown clock=%u static_string_id=%hu") == 0)
        return &command_encoder_81;
    if (__builtin_strcmp(str, "identify_response offset=%u data=%.*s") == 0)
        return &command_encoder_0;
    if (__builtin_strcmp(str, "stats count=%u sum=%u sumsq=%u") == 0)
        return &command_encoder_82;
    if (__builtin_strcmp(str, "uptime high=%u clock=%u") == 0)
        return &command_encoder_83;
    if (__builtin_strcmp(str, "clock clock=%u") == 0)
        return &command_encoder_84;
    if (__builtin_strcmp(str, "config is_config=%c crc=%u is_shutdown=%c move_count=%hu") == 0)
        return &command_encoder_85;
    if (__builtin_strcmp(str, "pong data=%*s") == 0)
        return &command_encoder_86;
    if (__builtin_strcmp(str, "debug_result val=%u") == 0)
        return &command_encoder_87;
    if (__builtin_strcmp(str, "stepper_position oid=%c pos=%i") == 0)
        return &command_encoder_88;
    if (__builtin_strcmp(str, "endstop_state oid=%c homing=%c next_clock=%u pin_value=%c") == 0)
        return &command_encoder_89;
    if (__builtin_strcmp(str, "trsync_state oid=%c can_trigger=%c trigger_reason=%c clock=%u") == 0)
        return &command_encoder_90;
    if (__builtin_strcmp(str, "analog_in_state oid=%c next_clock=%u value=%hu") == 0)
        return &command_encoder_91;
    if (__builtin_strcmp(str, "spi_transfer_response oid=%c response=%*s") == 0)
        return &command_encoder_92;
    if (__builtin_strcmp(str, "thermocouple_result oid=%c next_clock=%u value=%u fault=%c") == 0)
        return &command_encoder_93;
    if (__builtin_strcmp(str, "i2c_read_response oid=%c response=%*s") == 0)
        return &command_encoder_94;
    if (__builtin_strcmp(str, "adxl345_status oid=%c clock=%u query_ticks=%u next_sequence=%hu buffered=%c fifo=%c limit_count=%hu") == 0)
        return &command_encoder_95;
    if (__builtin_strcmp(str, "adxl345_data oid=%c sequence=%hu data=%*s") == 0)
        return &command_encoder_96;
    if (__builtin_strcmp(str, "spi_angle_transfer_response oid=%c clock=%u response=%*s") == 0)
        return &command_encoder_97;
    if (__builtin_strcmp(str, "spi_angle_end oid=%c sequence=%hu") == 0)
        return &command_encoder_98;
    if (__builtin_strcmp(str, "spi_angle_data oid=%c sequence=%hu data=%*s") == 0)
        return &command_encoder_99;
    if (__builtin_strcmp(str, "mpu9250_status oid=%c clock=%u query_ticks=%u next_sequence=%hu buffered=%c fifo=%u limit_count=%hu") == 0)
        return &command_encoder_100;
    if (__builtin_strcmp(str, "mpu9250_data oid=%c sequence=%hu data=%*s") == 0)
        return &command_encoder_101;
    if (__builtin_strcmp(str, "buttons_state oid=%c ack_count=%c state=%*s") == 0)
        return &command_encoder_102;
    if (__builtin_strcmp(str, "tmcuart_response oid=%c read=%*s") == 0)
        return &command_encoder_103;
    if (__builtin_strcmp(str, "neopixel_result oid=%c success=%c") == 0)
        return &command_encoder_104;
    if (__builtin_strcmp(str, "counter_state oid=%c next_clock=%u count=%u count_clock=%u") == 0)
        return &command_encoder_105;
    if (__builtin_strcmp(str, "t5uid1_received command=%c data=%*s") == 0)
        return &command_encoder_106;
    return NULL;
}

const __always_inline struct command_encoder *
ctr_lookup_output(const char *str)
{
    
    return NULL;
}

extern void command_allocate_oids(uint32_t*);
extern void command_buttons_ack(uint32_t*);
extern void command_buttons_add(uint32_t*);
extern void command_buttons_query(uint32_t*);
extern void command_clear_shutdown(uint32_t*);
extern void command_config_adxl345(uint32_t*);
extern void command_config_analog_in(uint32_t*);
extern void command_config_buttons(uint32_t*);
extern void command_config_counter(uint32_t*);
extern void command_config_digital_out(uint32_t*);
extern void command_config_endstop(uint32_t*);
extern void command_config_hd44780(uint32_t*);
extern void command_config_i2c(uint32_t*);
extern void command_config_mpu9250(uint32_t*);
extern void command_config_neopixel(uint32_t*);
extern void command_config_pwm_out(uint32_t*);
extern void command_config_spi(uint32_t*);
extern void command_config_spi_angle(uint32_t*);
extern void command_config_spi_shutdown(uint32_t*);
extern void command_config_spi_without_cs(uint32_t*);
extern void command_config_st7920(uint32_t*);
extern void command_config_stepper(uint32_t*);
extern void command_config_t5uid1(uint32_t*);
extern void command_config_thermocouple(uint32_t*);
extern void command_config_tmcuart(uint32_t*);
extern void command_config_trsync(uint32_t*);
extern void command_debug_nop(uint32_t*);
extern void command_debug_ping(uint32_t*);
extern void command_debug_read(uint32_t*);
extern void command_debug_write(uint32_t*);
extern void command_emergency_stop(uint32_t*);
extern void command_endstop_home(uint32_t*);
extern void command_endstop_query_state(uint32_t*);
extern void command_finalize_config(uint32_t*);
extern void command_get_clock(uint32_t*);
extern void command_get_config(uint32_t*);
extern void command_get_uptime(uint32_t*);
extern void command_hd44780_send_cmds(uint32_t*);
extern void command_hd44780_send_data(uint32_t*);
extern void command_i2c_modify_bits(uint32_t*);
extern void command_i2c_read(uint32_t*);
extern void command_i2c_write(uint32_t*);
extern void command_identify(uint32_t*);
extern void command_neopixel_send(uint32_t*);
extern void command_neopixel_update(uint32_t*);
extern void command_query_adxl345(uint32_t*);
extern void command_query_adxl345_status(uint32_t*);
extern void command_query_analog_in(uint32_t*);
extern void command_query_counter(uint32_t*);
extern void command_query_mpu9250(uint32_t*);
extern void command_query_mpu9250_status(uint32_t*);
extern void command_query_spi_angle(uint32_t*);
extern void command_query_thermocouple(uint32_t*);
extern void command_queue_digital_out(uint32_t*);
extern void command_queue_pwm_out(uint32_t*);
extern void command_queue_step(uint32_t*);
extern void command_reset(uint32_t*);
extern void command_reset_step_clock(uint32_t*);
extern void command_set_digital_out(uint32_t*);
extern void command_set_digital_out_pwm_cycle(uint32_t*);
extern void command_set_next_step_dir(uint32_t*);
extern void command_set_pwm_out(uint32_t*);
extern void command_spi_angle_transfer(uint32_t*);
extern void command_spi_send(uint32_t*);
extern void command_spi_set_bus(uint32_t*);
extern void command_spi_set_software_bus(uint32_t*);
extern void command_spi_transfer(uint32_t*);
extern void command_st7920_send_cmds(uint32_t*);
extern void command_st7920_send_data(uint32_t*);
extern void command_stepper_get_position(uint32_t*);
extern void command_stepper_stop_on_trigger(uint32_t*);
extern void command_t5uid1_ping(uint32_t*);
extern void command_t5uid1_write(uint32_t*);
extern void command_tmcuart_send(uint32_t*);
extern void command_trsync_set_timeout(uint32_t*);
extern void command_trsync_start(uint32_t*);
extern void command_trsync_trigger(uint32_t*);
extern void command_update_digital_out(uint32_t*);

const struct command_parser command_index[] PROGMEM = {
{
}, {
    // identify offset=%u count=%c
    .msg_id=1,
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0x01,
    .func=command_identify
}, {
    // clear_shutdown
    .msg_id=2,
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_clear_shutdown
}, {
    // emergency_stop
    .msg_id=3,
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_emergency_stop
}, {
    // get_uptime
    .msg_id=4,
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_uptime
}, {
    // get_clock
    .msg_id=5,
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_clock
}, {
    // finalize_config crc=%u
    .msg_id=6,
    .num_params=1,
    .param_types = command_parameters5,
    .num_args=1,
    .flags=0,
    .func=command_finalize_config
}, {
    // get_config
    .msg_id=7,
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_config
}, {
    // allocate_oids count=%c
    .msg_id=8,
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_allocate_oids
}, {
    // debug_nop
    .msg_id=9,
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_debug_nop
}, {
    // debug_ping data=%*s
    .msg_id=10,
    .num_params=1,
    .param_types = command_parameters7,
    .num_args=2,
    .flags=0x01,
    .func=command_debug_ping
}, {
    // debug_write order=%c addr=%u val=%u
    .msg_id=11,
    .num_params=3,
    .param_types = command_parameters24,
    .num_args=3,
    .flags=0x01,
    .func=command_debug_write
}, {
    // debug_read order=%c addr=%u
    .msg_id=12,
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0x01,
    .func=command_debug_read
}, {
    // set_digital_out pin=%u value=%c
    .msg_id=13,
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_set_digital_out
}, {
    // update_digital_out oid=%c value=%c
    .msg_id=14,
    .num_params=2,
    .param_types = command_parameters20,
    .num_args=2,
    .flags=0,
    .func=command_update_digital_out
}, {
    // queue_digital_out oid=%c clock=%u on_ticks=%u
    .msg_id=15,
    .num_params=3,
    .param_types = command_parameters24,
    .num_args=3,
    .flags=0,
    .func=command_queue_digital_out
}, {
    // set_digital_out_pwm_cycle oid=%c cycle_ticks=%u
    .msg_id=16,
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_set_digital_out_pwm_cycle
}, {
    // config_digital_out oid=%c pin=%u value=%c default_value=%c max_duration=%u
    .msg_id=17,
    .num_params=5,
    .param_types = command_parameters26,
    .num_args=5,
    .flags=0,
    .func=command_config_digital_out
}, {
    // stepper_stop_on_trigger oid=%c trsync_oid=%c
    .msg_id=18,
    .num_params=2,
    .param_types = command_parameters20,
    .num_args=2,
    .flags=0,
    .func=command_stepper_stop_on_trigger
}, {
    // stepper_get_position oid=%c
    .msg_id=19,
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_stepper_get_position
}, {
    // reset_step_clock oid=%c clock=%u
    .msg_id=20,
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_reset_step_clock
}, {
    // set_next_step_dir oid=%c dir=%c
    .msg_id=21,
    .num_params=2,
    .param_types = command_parameters20,
    .num_args=2,
    .flags=0,
    .func=command_set_next_step_dir
}, {
    // queue_step oid=%c interval=%u count=%hu add=%hi
    .msg_id=22,
    .num_params=4,
    .param_types = command_parameters27,
    .num_args=4,
    .flags=0,
    .func=command_queue_step
}, {
    // config_stepper oid=%c step_pin=%c dir_pin=%c invert_step=%c step_pulse_ticks=%u
    .msg_id=23,
    .num_params=5,
    .param_types = command_parameters28,
    .num_args=5,
    .flags=0,
    .func=command_config_stepper
}, {
    // endstop_query_state oid=%c
    .msg_id=24,
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_endstop_query_state
}, {
    // endstop_home oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u pin_value=%c trsync_oid=%c trigger_reason=%c
    .msg_id=25,
    .num_params=8,
    .param_types = command_parameters29,
    .num_args=8,
    .flags=0,
    .func=command_endstop_home
}, {
    // config_endstop oid=%c pin=%c pull_up=%c
    .msg_id=26,
    .num_params=3,
    .param_types = command_parameters30,
    .num_args=3,
    .flags=0,
    .func=command_config_endstop
}, {
    // trsync_trigger oid=%c reason=%c
    .msg_id=27,
    .num_params=2,
    .param_types = command_parameters20,
    .num_args=2,
    .flags=0,
    .func=command_trsync_trigger
}, {
    // trsync_set_timeout oid=%c clock=%u
    .msg_id=28,
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_trsync_set_timeout
}, {
    // trsync_start oid=%c report_clock=%u report_ticks=%u expire_reason=%c
    .msg_id=29,
    .num_params=4,
    .param_types = command_parameters13,
    .num_args=4,
    .flags=0,
    .func=command_trsync_start
}, {
    // config_trsync oid=%c
    .msg_id=30,
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_config_trsync
}, {
    // query_analog_in oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u min_value=%hu max_value=%hu range_check_count=%c
    .msg_id=31,
    .num_params=8,
    .param_types = command_parameters31,
    .num_args=8,
    .flags=0,
    .func=command_query_analog_in
}, {
    // config_analog_in oid=%c pin=%u
    .msg_id=32,
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_config_analog_in
}, {
    // config_spi_shutdown oid=%c spi_oid=%c shutdown_msg=%*s
    .msg_id=33,
    .num_params=3,
    .param_types = command_parameters19,
    .num_args=4,
    .flags=0,
    .func=command_config_spi_shutdown
}, {
    // spi_send oid=%c data=%*s
    .msg_id=34,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_spi_send
}, {
    // spi_transfer oid=%c data=%*s
    .msg_id=35,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_spi_transfer
}, {
    // spi_set_bus oid=%c spi_bus=%u mode=%u rate=%u
    .msg_id=36,
    .num_params=4,
    .param_types = command_parameters21,
    .num_args=4,
    .flags=0,
    .func=command_spi_set_bus
}, {
    // config_spi_without_cs oid=%c
    .msg_id=37,
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_config_spi_without_cs
}, {
    // config_spi oid=%c pin=%u cs_active_high=%c
    .msg_id=38,
    .num_params=3,
    .param_types = command_parameters32,
    .num_args=3,
    .flags=0,
    .func=command_config_spi
}, {
    // query_thermocouple oid=%c clock=%u rest_ticks=%u min_value=%u max_value=%u
    .msg_id=39,
    .num_params=5,
    .param_types = command_parameters33,
    .num_args=5,
    .flags=0,
    .func=command_query_thermocouple
}, {
    // config_thermocouple oid=%c spi_oid=%c thermocouple_type=%c
    .msg_id=40,
    .num_params=3,
    .param_types = command_parameters30,
    .num_args=3,
    .flags=0,
    .func=command_config_thermocouple
}, {
    // i2c_modify_bits oid=%c reg=%*s clear_set_bits=%*s
    .msg_id=41,
    .num_params=3,
    .param_types = command_parameters34,
    .num_args=5,
    .flags=0,
    .func=command_i2c_modify_bits
}, {
    // i2c_read oid=%c reg=%*s read_len=%u
    .msg_id=42,
    .num_params=3,
    .param_types = command_parameters35,
    .num_args=4,
    .flags=0,
    .func=command_i2c_read
}, {
    // i2c_write oid=%c data=%*s
    .msg_id=43,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_i2c_write
}, {
    // config_i2c oid=%c i2c_bus=%u rate=%u address=%u
    .msg_id=44,
    .num_params=4,
    .param_types = command_parameters21,
    .num_args=4,
    .flags=0,
    .func=command_config_i2c
}, {
    // set_pwm_out pin=%u cycle_ticks=%u value=%hu
    .msg_id=45,
    .num_params=3,
    .param_types = command_parameters36,
    .num_args=3,
    .flags=0,
    .func=command_set_pwm_out
}, {
    // queue_pwm_out oid=%c clock=%u value=%hu
    .msg_id=46,
    .num_params=3,
    .param_types = command_parameters11,
    .num_args=3,
    .flags=0,
    .func=command_queue_pwm_out
}, {
    // config_pwm_out oid=%c pin=%u cycle_ticks=%u value=%hu default_value=%hu max_duration=%u
    .msg_id=47,
    .num_params=6,
    .param_types = command_parameters37,
    .num_args=6,
    .flags=0,
    .func=command_config_pwm_out
}, {
    // spi_set_software_bus oid=%c miso_pin=%u mosi_pin=%u sclk_pin=%u mode=%u rate=%u
    .msg_id=48,
    .num_params=6,
    .param_types = command_parameters38,
    .num_args=6,
    .flags=0,
    .func=command_spi_set_software_bus
}, {
    // query_adxl345_status oid=%c
    .msg_id=49,
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_adxl345_status
}, {
    // query_adxl345 oid=%c clock=%u rest_ticks=%u
    .msg_id=50,
    .num_params=3,
    .param_types = command_parameters24,
    .num_args=3,
    .flags=0,
    .func=command_query_adxl345
}, {
    // config_adxl345 oid=%c spi_oid=%c
    .msg_id=51,
    .num_params=2,
    .param_types = command_parameters20,
    .num_args=2,
    .flags=0,
    .func=command_config_adxl345
}, {
    // spi_angle_transfer oid=%c data=%*s
    .msg_id=52,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_spi_angle_transfer
}, {
    // query_spi_angle oid=%c clock=%u rest_ticks=%u time_shift=%c
    .msg_id=53,
    .num_params=4,
    .param_types = command_parameters13,
    .num_args=4,
    .flags=0,
    .func=command_query_spi_angle
}, {
    // config_spi_angle oid=%c spi_oid=%c spi_angle_type=%c
    .msg_id=54,
    .num_params=3,
    .param_types = command_parameters30,
    .num_args=3,
    .flags=0,
    .func=command_config_spi_angle
}, {
    // query_mpu9250_status oid=%c
    .msg_id=55,
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_mpu9250_status
}, {
    // query_mpu9250 oid=%c clock=%u rest_ticks=%u
    .msg_id=56,
    .num_params=3,
    .param_types = command_parameters24,
    .num_args=3,
    .flags=0,
    .func=command_query_mpu9250
}, {
    // config_mpu9250 oid=%c i2c_oid=%c
    .msg_id=57,
    .num_params=2,
    .param_types = command_parameters20,
    .num_args=2,
    .flags=0,
    .func=command_config_mpu9250
}, {
    // st7920_send_data oid=%c data=%*s
    .msg_id=58,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_st7920_send_data
}, {
    // st7920_send_cmds oid=%c cmds=%*s
    .msg_id=59,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_st7920_send_cmds
}, {
    // config_st7920 oid=%c cs_pin=%u sclk_pin=%u sid_pin=%u sync_delay_ticks=%u cmd_delay_ticks=%u
    .msg_id=60,
    .num_params=6,
    .param_types = command_parameters38,
    .num_args=6,
    .flags=0,
    .func=command_config_st7920
}, {
    // hd44780_send_data oid=%c data=%*s
    .msg_id=61,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_hd44780_send_data
}, {
    // hd44780_send_cmds oid=%c cmds=%*s
    .msg_id=62,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_hd44780_send_cmds
}, {
    // config_hd44780 oid=%c rs_pin=%u e_pin=%u d4_pin=%u d5_pin=%u d6_pin=%u d7_pin=%u delay_ticks=%u
    .msg_id=63,
    .num_params=8,
    .param_types = command_parameters39,
    .num_args=8,
    .flags=0,
    .func=command_config_hd44780
}, {
    // buttons_ack oid=%c count=%c
    .msg_id=64,
    .num_params=2,
    .param_types = command_parameters20,
    .num_args=2,
    .flags=0,
    .func=command_buttons_ack
}, {
    // buttons_query oid=%c clock=%u rest_ticks=%u retransmit_count=%c invert=%c
    .msg_id=65,
    .num_params=5,
    .param_types = command_parameters40,
    .num_args=5,
    .flags=0,
    .func=command_buttons_query
}, {
    // buttons_add oid=%c pos=%c pin=%u pull_up=%c
    .msg_id=66,
    .num_params=4,
    .param_types = command_parameters9,
    .num_args=4,
    .flags=0,
    .func=command_buttons_add
}, {
    // config_buttons oid=%c button_count=%c
    .msg_id=67,
    .num_params=2,
    .param_types = command_parameters20,
    .num_args=2,
    .flags=0,
    .func=command_config_buttons
}, {
    // tmcuart_send oid=%c write=%*s read=%c
    .msg_id=68,
    .num_params=3,
    .param_types = command_parameters41,
    .num_args=4,
    .flags=0,
    .func=command_tmcuart_send
}, {
    // config_tmcuart oid=%c rx_pin=%u pull_up=%c tx_pin=%u bit_time=%u
    .msg_id=69,
    .num_params=5,
    .param_types = command_parameters42,
    .num_args=5,
    .flags=0,
    .func=command_config_tmcuart
}, {
    // neopixel_send oid=%c
    .msg_id=70,
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_neopixel_send
}, {
    // neopixel_update oid=%c pos=%hu data=%*s
    .msg_id=71,
    .num_params=3,
    .param_types = command_parameters15,
    .num_args=4,
    .flags=0,
    .func=command_neopixel_update
}, {
    // config_neopixel oid=%c pin=%u data_size=%hu bit_max_ticks=%u reset_min_ticks=%u
    .msg_id=72,
    .num_params=5,
    .param_types = command_parameters43,
    .num_args=5,
    .flags=0,
    .func=command_config_neopixel
}, {
    // query_counter oid=%c clock=%u poll_ticks=%u sample_ticks=%u
    .msg_id=73,
    .num_params=4,
    .param_types = command_parameters21,
    .num_args=4,
    .flags=0,
    .func=command_query_counter
}, {
    // config_counter oid=%c pin=%u pull_up=%c
    .msg_id=74,
    .num_params=3,
    .param_types = command_parameters32,
    .num_args=3,
    .flags=0,
    .func=command_config_counter
}, {
    // reset
    .msg_id=75,
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_reset
}, {
    // t5uid1_write oid=%c command=%c data=%*s
    .msg_id=76,
    .num_params=3,
    .param_types = command_parameters19,
    .num_args=4,
    .flags=0x01,
    .func=command_t5uid1_write
}, {
    // t5uid1_ping oid=%c
    .msg_id=77,
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0x01,
    .func=command_t5uid1_ping
}, {
    // config_t5uid1 oid=%c baud=%u timeout=%hu timeout_command=%c timeout_data=%*s
    .msg_id=78,
    .num_params=5,
    .param_types = command_parameters44,
    .num_args=6,
    .flags=0,
    .func=command_config_t5uid1
},
};

const uint8_t command_index_size PROGMEM = ARRAY_SIZE(command_index);

// version: 128aaac-dirty-20220926_091058-raspberrypi
// build_versions: gcc: (GCC) 5.4.0 binutils: (GNU Binutils) 2.26.20160125

const uint8_t command_identify_data[] PROGMEM = {
    0x78, 0xda, 0xa5, 0x59, 0xe9, 0x6e, 0xdc, 0xc8,
    0x11, 0x7e, 0x95, 0xde, 0x01, 0x8c, 0x64, 0x03,
    0xc9, 0x98, 0xe1, 0x90, 0x73, 0x28, 0xf0, 0x0f,
    0x5d, 0x5e, 0x7b, 0xd7, 0xb2, 0xb5, 0x96, 0x15,
    0x07, 0x08, 0x02, 0xa2, 0x45, 0xf6, 0xcc, 0x34,
    0xc4, 0x6b, 0xd9, 0xa4, 0x8e, 0x2c, 0xf4, 0xee,
    0xa9, 0xea, 0xea, 0x8b, 0x9c, 0xb1, 0x77, 0x91,
    0x18, 0x30, 0xc4, 0xee, 0xae, 0xea, 0xa3, 0x8e,
    0xaf, 0x8e, 0xf9, 0x7d, 0x72, 0xd7, 0xcb, 0x22,
    0x4f, 0x1f, 0x44, 0xab, 0x64, 0x5d, 0xa9, 0xc9,
    0xc9, 0x64, 0x9b, 0x65, 0x27, 0xec, 0xaf, 0x3f,
    0x9d, 0x9f, 0xff, 0xc8, 0x92, 0xd7, 0xf1, 0xeb,
    0x29, 0xbb, 0x93, 0x55, 0xdf, 0xc9, 0x42, 0xe1,
    0xec, 0xc7, 0x5b, 0x76, 0x66, 0x86, 0x3f, 0xb2,
    0xe8, 0x75, 0xb4, 0x78, 0x1d, 0x4d, 0x67, 0x8b,
    0xe9, 0x2c, 0x4a, 0x26, 0x47, 0x93, 0xac, 0x2e,
    0x4b, 0x5e, 0xe5, 0xb0, 0xc9, 0xef, 0x13, 0x5e,
    0x14, 0x75, 0xc6, 0x3b, 0x91, 0xd6, 0x32, 0x57,
    0x2c, 0xab, 0xfb, 0xaa, 0x7b, 0xf3, 0x2a, 0x9b,
    0x9c, 0xac, 0x8e, 0xe0, 0xc4, 0xae, 0x83, 0xa3,
    0x52, 0x9e, 0xdd, 0x33, 0x58, 0x85, 0xe9, 0x60,
    0x7d, 0x11, 0x07, 0x04, 0x79, 0x6e, 0x09, 0x9a,
    0x5a, 0xe9, 0x3f, 0xb2, 0x7a, 0xf3, 0xaa, 0x67,
    0x4d, 0x5f, 0x14, 0x69, 0xdf, 0x10, 0xc3, 0xc2,
    0x33, 0xfc, 0xd6, 0x8b, 0xf6, 0xd9, 0xed, 0x09,
    0x17, 0xb8, 0x47, 0xea, 0x56, 0xa8, 0x2e, 0xed,
    0x64, 0x76, 0xaf, 0x68, 0xd4, 0xb5, 0xbc, 0x52,
    0xa5, 0xec, 0x52, 0x7b, 0x2a, 0x93, 0x15, 0xbc,
    0xdf, 0x9c, 0x9f, 0xc0, 0x3b, 0x0a, 0xc1, 0xdb,
    0x54, 0xed, 0xfa, 0x2e, 0xaf, 0x1f, 0xab, 0xc9,
    0x49, 0x84, 0x4f, 0xab, 0x36, 0x72, 0x0b, 0x37,
    0x7a, 0x2a, 0xe6, 0x71, 0x62, 0x8f, 0x50, 0x8d,
    0x4c, 0xe9, 0x73, 0x72, 0x92, 0xcc, 0x3c, 0x55,
    0xc5, 0x8b, 0x7a, 0x9b, 0xca, 0xca, 0xdd, 0x5e,
    0x5f, 0x7b, 0x72, 0x32, 0xf7, 0x3b, 0x99, 0x2b,
    0x5b, 0x0a, 0x1a, 0xa6, 0x81, 0x1c, 0x96, 0x8e,
    0x54, 0x4f, 0x8a, 0x76, 0xb8, 0xd9, 0x40, 0x06,
    0xcb, 0xd8, 0x11, 0xe7, 0x72, 0x2b, 0x3b, 0x5e,
    0xa4, 0x75, 0xdf, 0x8d, 0x18, 0x1e, 0x78, 0xd1,
    0x0b, 0x1c, 0xe7, 0x62, 0xc3, 0xfb, 0xa2, 0x4b,
    0xdd, 0x44, 0xc9, 0x9f, 0xd2, 0xbc, 0x6f, 0x79,
    0x07, 0x16, 0xa0, 0xef, 0x39, 0xf3, 0x87, 0x0b,
    0xd0, 0x67, 0x57, 0x37, 0x83, 0xbd, 0xb2, 0xc1,
    0xe1, 0xd1, 0xc2, 0x11, 0xef, 0xf2, 0x38, 0x5e,
    0xae, 0xa6, 0x96, 0xb8, 0x55, 0xa9, 0x39, 0x5b,
    0xd8, 0x8f, 0x3c, 0x76, 0x5f, 0x89, 0xfb, 0x5a,
    0xb8, 0xaf, 0xa5, 0xfb, 0x12, 0x05, 0x7f, 0x76,
    0x4a, 0x03, 0x71, 0xcc, 0xdd, 0x21, 0x32, 0xca,
    0xec, 0x01, 0xf0, 0x09, 0x82, 0x24, 0xb5, 0x82,
    0xad, 0xe1, 0x5f, 0xb0, 0x19, 0xd0, 0x37, 0x31,
    0xc5, 0x5e, 0x2c, 0x65, 0xd3, 0xaf, 0xa3, 0x64,
    0x1a, 0x32, 0x3a, 0xc5, 0xf9, 0xc7, 0x56, 0xa2,
    0x6e, 0xe4, 0x93, 0x28, 0x46, 0x92, 0xcb, 0x79,
    0xc7, 0x53, 0x25, 0xff, 0x03, 0x07, 0xec, 0x7a,
    0x70, 0x87, 0x2e, 0x45, 0x89, 0x05, 0x16, 0xa5,
    0x04, 0x4c, 0xc9, 0x2a, 0xb8, 0xef, 0xd2, 0x6b,
    0xba, 0x79, 0x2c, 0x0f, 0x68, 0x23, 0x7b, 0x06,
    0x2b, 0xf3, 0x7b, 0x18, 0x5d, 0xec, 0xfa, 0xb1,
    0x76, 0x60, 0x66, 0x4f, 0x3d, 0xb1, 0xbf, 0x31,
    0x58, 0xe0, 0x78, 0x63, 0x74, 0xac, 0x4e, 0x3e,
    0x88, 0x74, 0x27, 0xb7, 0x3b, 0xfd, 0xc2, 0xf9,
    0x2a, 0xa4, 0x07, 0xf3, 0xdc, 0x16, 0x62, 0xdf,
    0x84, 0x99, 0x5b, 0x4b, 0xbb, 0xe7, 0x46, 0x90,
    0x6c, 0xe2, 0x01, 0xa7, 0x75, 0x89, 0x43, 0xcc,
    0x66, 0x29, 0x2d, 0xd5, 0xf6, 0xcd, 0xab, 0xbf,
    0x01, 0x06, 0xcc, 0xe7, 0x03, 0xde, 0x47, 0xd9,
    0xed, 0x40, 0x0c, 0x69, 0x66, 0x6d, 0x1e, 0x28,
    0x82, 0x77, 0x74, 0xcb, 0x75, 0xe4, 0xd4, 0x93,
    0x39, 0xc3, 0x51, 0x59, 0x71, 0xef, 0xbe, 0x65,
    0xee, 0x3e, 0x9f, 0xab, 0x2c, 0x1d, 0xda, 0x08,
    0xcb, 0xca, 0x3c, 0xdd, 0x33, 0x9b, 0x69, 0x70,
    0x82, 0x68, 0x1a, 0xef, 0x45, 0x38, 0x4c, 0x8d,
    0x35, 0xe7, 0xb2, 0xb5, 0x9f, 0x84, 0x04, 0x9a,
    0xd8, 0x53, 0xf5, 0x85, 0x12, 0xc1, 0xa6, 0x91,
    0x7f, 0x58, 0x97, 0xf4, 0x32, 0x9f, 0x39, 0x27,
    0xe6, 0x7d, 0x8e, 0x37, 0xe9, 0x64, 0x29, 0xe0,
    0xa9, 0x5a, 0x79, 0xe6, 0x3b, 0x35, 0xd8, 0x88,
    0x64, 0x76, 0x0a, 0xcd, 0x8a, 0x44, 0xb5, 0xf4,
    0x0a, 0xea, 0x76, 0xa2, 0x2d, 0x6b, 0x70, 0xf9,
    0xe6, 0xa0, 0x8e, 0xc2, 0x65, 0xaf, 0xa6, 0xd8,
    0x3f, 0xb3, 0x2b, 0xb3, 0x9e, 0xb7, 0xce, 0xda,
    0xda, 0xa7, 0x74, 0x0f, 0x2f, 0x58, 0xe7, 0x26,
    0xd1, 0x96, 0xf1, 0x3a, 0x24, 0xac, 0xb5, 0xdf,
    0xa5, 0x45, 0x09, 0x7b, 0x45, 0xc1, 0xfe, 0xb9,
    0xb8, 0xeb, 0xc1, 0x43, 0xea, 0x66, 0x72, 0xb2,
    0xb6, 0x23, 0xd8, 0x65, 0xcb, 0xfc, 0x33, 0x66,
    0x8e, 0xac, 0x15, 0x1c, 0xa0, 0xbb, 0xcd, 0x45,
    0x8b, 0xe7, 0xa1, 0x4f, 0x12, 0xae, 0x44, 0x96,
    0xe0, 0xb1, 0x95, 0x9d, 0xd8, 0xa3, 0x40, 0x37,
    0x20, 0x42, 0x00, 0x53, 0x51, 0x8a, 0x76, 0x2b,
    0xaa, 0xec, 0x39, 0x45, 0x00, 0x82, 0x4b, 0xc0,
    0x14, 0x81, 0x51, 0xba, 0xab, 0x4b, 0xb1, 0x07,
    0xf3, 0x8a, 0x97, 0x4d, 0xe8, 0x52, 0x66, 0xec,
    0x40, 0x7e, 0x18, 0x06, 0xe0, 0xea, 0x1e, 0x00,
    0xe9, 0xb9, 0x4e, 0xc6, 0xad, 0xdc, 0x6e, 0x45,
    0x8b, 0x8f, 0x50, 0xe8, 0x71, 0x88, 0x71, 0x89,
    0x3f, 0x5c, 0x07, 0x19, 0xb8, 0x13, 0xef, 0x84,
    0x13, 0x50, 0x04, 0x7e, 0xb2, 0x91, 0x00, 0xfb,
    0x00, 0x12, 0x29, 0xc9, 0x90, 0x65, 0x6d, 0x46,
    0x62, 0x3d, 0x9a, 0x6c, 0x01, 0x1f, 0xf4, 0x3d,
    0xc1, 0xa3, 0xcc, 0x48, 0xd3, 0x80, 0xe6, 0x69,
    0xd8, 0x37, 0xa8, 0x05, 0x50, 0xe4, 0xd1, 0xc4,
    0x60, 0x68, 0xaa, 0xe0, 0xbc, 0x14, 0x6c, 0xda,
    0x85, 0x08, 0xfc, 0x26, 0x39, 0x2f, 0xa2, 0x11,
    0x19, 0xaa, 0xc0, 0x92, 0x79, 0x75, 0x2c, 0x40,
    0x88, 0x08, 0x74, 0x65, 0x9d, 0xcb, 0xcd, 0x73,
    0x0a, 0xba, 0x76, 0x7b, 0xb5, 0x42, 0x3b, 0x29,
    0x33, 0x91, 0x0e, 0x6e, 0x80, 0xab, 0xc4, 0x16,
    0x1b, 0x36, 0xd2, 0xe1, 0x90, 0x1e, 0xe7, 0xd2,
    0x42, 0x18, 0x18, 0x8a, 0x88, 0xd0, 0xe8, 0x72,
    0x7c, 0x7c, 0x0c, 0x0a, 0x93, 0xb9, 0xa8, 0x3a,
    0x38, 0x9c, 0xd5, 0x9b, 0x0d, 0x9c, 0xa2, 0xdd,
    0xd4, 0x85, 0x38, 0x38, 0xc7, 0x02, 0xae, 0x7e,
    0x86, 0x93, 0xe6, 0x72, 0x1a, 0xac, 0xf4, 0x4d,
    0xee, 0x25, 0x4d, 0x79, 0xc0, 0xae, 0x0f, 0x8e,
    0x59, 0xc2, 0x36, 0xa4, 0x92, 0x51, 0x70, 0x3e,
    0x1c, 0xff, 0x41, 0x03, 0xd3, 0x11, 0x83, 0xd6,
    0x65, 0xef, 0x61, 0x29, 0x5e, 0x3b, 0x82, 0x71,
    0x20, 0xff, 0x1f, 0x8d, 0xad, 0xf4, 0xc6, 0x66,
    0xf0, 0xdc, 0x8f, 0x20, 0x19, 0xd9, 0x02, 0xe3,
    0x4e, 0x64, 0xf7, 0x41, 0xf8, 0x9f, 0xbb, 0x57,
    0x8d, 0xa2, 0xbf, 0xbb, 0x41, 0x53, 0x83, 0x3f,
    0x8f, 0xcf, 0x0f, 0x02, 0xd0, 0xdc, 0x6e, 0x30,
    0x0a, 0x7d, 0xdf, 0x14, 0xcb, 0x62, 0xc4, 0x30,
    0x16, 0x4b, 0x92, 0x58, 0x82, 0xbd, 0x20, 0xf2,
    0x8d, 0x54, 0x0b, 0x6d, 0x1a, 0x62, 0x86, 0xdc,
    0xd0, 0x9b, 0x12, 0x77, 0xa5, 0x43, 0x20, 0xf7,
    0x8d, 0x3d, 0x02, 0xd1, 0x0d, 0x24, 0x87, 0xd9,
    0x14, 0xe9, 0xa9, 0x17, 0x87, 0x92, 0x1e, 0xb7,
    0x5d, 0x1d, 0x86, 0xe5, 0x59, 0x62, 0x59, 0x46,
    0x51, 0xd9, 0x91, 0x3b, 0xc5, 0x80, 0x1d, 0x2c,
    0x2c, 0x31, 0x86, 0x01, 0x97, 0x3a, 0xa0, 0x36,
    0x08, 0xa7, 0xac, 0x2d, 0xef, 0x74, 0xda, 0x01,
    0x7f, 0x25, 0x20, 0x01, 0x38, 0x85, 0x4e, 0x08,
    0x40, 0x05, 0x89, 0xf9, 0xd4, 0xfc, 0x04, 0x00,
    0xe3, 0xf3, 0x80, 0x01, 0xcc, 0x11, 0x69, 0xc2,
    0x37, 0x8c, 0x32, 0x36, 0xb8, 0xf7, 0x7c, 0x8f,
    0x48, 0xbf, 0x40, 0x67, 0x11, 0x6e, 0xcf, 0x41,
    0x4a, 0x01, 0x4c, 0x0b, 0x62, 0xaa, 0xc4, 0x93,
    0xb9, 0x02, 0x04, 0x3a, 0xe7, 0xa7, 0xb2, 0x25,
    0xe4, 0x9a, 0x11, 0x91, 0x95, 0xc7, 0x1f, 0xa4,
    0x27, 0x20, 0x15, 0x78, 0x55, 0x90, 0x29, 0x60,
    0x2e, 0xbd, 0xf1, 0xe6, 0xe9, 0xfd, 0x32, 0x89,
    0x88, 0x2e, 0xf0, 0xec, 0x60, 0x75, 0x1e, 0xdb,
    0xd5, 0x0e, 0x33, 0xb8, 0x30, 0xd2, 0x99, 0x84,
    0x0e, 0x50, 0x4b, 0x04, 0x89, 0x1d, 0xb0, 0x2c,
    0x3c, 0x8b, 0xaa, 0x37, 0xdd, 0x23, 0x6f, 0x45,
    0xc8, 0x5b, 0x4a, 0x55, 0xdb, 0xb8, 0x56, 0xd6,
    0x4a, 0x1e, 0x4a, 0x21, 0xf6, 0x36, 0x8d, 0x57,
    0xb4, 0xe9, 0xb7, 0xdf, 0x31, 0xc7, 0xf7, 0xea,
    0xec, 0xe4, 0x7b, 0x90, 0x9c, 0xac, 0x87, 0x54,
    0x87, 0x11, 0x39, 0xc1, 0xd3, 0x28, 0x0f, 0x49,
    0x11, 0xf6, 0x01, 0xcd, 0x24, 0x66, 0x75, 0xce,
    0xc7, 0x66, 0x6b, 0x4f, 0xa0, 0x83, 0x0d, 0x5a,
    0x2f, 0x85, 0x23, 0xe6, 0xa2, 0x53, 0x10, 0xab,
    0x80, 0x03, 0xb6, 0xa4, 0x2c, 0x84, 0xa2, 0xb1,
    0xc3, 0xd0, 0xa5, 0x9b, 0x1f, 0xe0, 0x73, 0x90,
    0x87, 0x04, 0x18, 0x0a, 0xa2, 0x35, 0x89, 0xc3,
    0x40, 0x5f, 0x9a, 0xd3, 0x01, 0x3f, 0xd5, 0x25,
    0x78, 0x1e, 0x5d, 0x01, 0x15, 0x61, 0x72, 0x99,
    0x03, 0x66, 0x1d, 0xd0, 0x75, 0x61, 0x42, 0x22,
    0x9a, 0xba, 0x35, 0xd1, 0x90, 0xbc, 0x5d, 0x8f,
    0x9d, 0xa5, 0x89, 0xa7, 0x46, 0x82, 0x5e, 0xc3,
    0xd8, 0xbb, 0x76, 0x3b, 0x8d, 0x44, 0x11, 0x12,
    0xc1, 0x73, 0x29, 0x52, 0x1c, 0x02, 0x83, 0xc0,
    0x91, 0xe2, 0x17, 0x9b, 0xe4, 0x60, 0x95, 0x7a,
    0x7a, 0x71, 0x9e, 0x5e, 0x9d, 0xfe, 0x13, 0x53,
    0x17, 0xcc, 0xea, 0xce, 0x6e, 0x6f, 0xd2, 0xeb,
    0xf7, 0x1f, 0x6f, 0x10, 0xe1, 0xa0, 0x12, 0xbe,
    0x3e, 0x9b, 0x1f, 0x5d, 0x9f, 0x45, 0xf0, 0x7f,
    0x36, 0x09, 0x16, 0xbb, 0x47, 0xbd, 0x78, 0x31,
    0x3d, 0xba, 0xbe, 0xc0, 0x85, 0xf3, 0x0f, 0x9f,
    0xce, 0x7f, 0x49, 0xdf, 0x7e, 0xbe, 0xfc, 0x15,
    0x7d, 0x6e, 0xaa, 0xff, 0x1d, 0x4d, 0xae, 0xce,
    0x6f, 0x81, 0x8a, 0x77, 0xa5, 0xd8, 0xf2, 0x28,
    0x59, 0x4c, 0x81, 0xf0, 0xfa, 0xeb, 0x15, 0x9d,
    0x16, 0x21, 0x96, 0x7e, 0xbe, 0x3c, 0xbf, 0x7c,
    0xff, 0x8f, 0xcb, 0xf4, 0xeb, 0xfb, 0x8f, 0x17,
    0x9f, 0xbe, 0xa2, 0xee, 0x23, 0x9c, 0xbc, 0xb9,
    0xfc, 0x0c, 0x93, 0x74, 0x0b, 0xd1, 0x4a, 0x5e,
    0xe0, 0x59, 0x97, 0x70, 0xd6, 0x25, 0x9e, 0x35,
    0x58, 0x27, 0xfd, 0xe2, 0xfa, 0x3b, 0x58, 0x7f,
    0x87, 0xeb, 0xb0, 0xfa, 0xfe, 0xf4, 0x43, 0x7a,
    0x76, 0x7a, 0x7b, 0x81, 0x59, 0x54, 0x12, 0xe1,
    0x55, 0x6e, 0xbe, 0x9c, 0x7e, 0xb9, 0x49, 0x6f,
    0x6e, 0xaf, 0x6e, 0x7e, 0x85, 0x95, 0x9b, 0x4b,
    0xbc, 0xc0, 0xe2, 0x05, 0x33, 0x9a, 0x1e, 0x72,
    0x2c, 0x5d, 0x57, 0xe8, 0x9a, 0xdd, 0x94, 0x53,
    0xf8, 0xa9, 0xdf, 0x38, 0x05, 0x1a, 0x30, 0x2a,
    0x1c, 0x5f, 0x9f, 0x4e, 0x27, 0x27, 0xff, 0x9a,
    0x1e, 0xad, 0xfe, 0x0d, 0xcf, 0x38, 0xc3, 0xef,
    0x15, 0x7d, 0x9f, 0xe3, 0x37, 0x20, 0x8d, 0x1e,
    0x5c, 0xe0, 0x00, 0x72, 0x21, 0x3d, 0xb8, 0xc4,
    0x01, 0x54, 0xbc, 0x7a, 0xf0, 0x16, 0x07, 0xb1,
    0xe1, 0xff, 0x49, 0x0f, 0xcc, 0x06, 0xef, 0x70,
    0x90, 0x98, 0x0d, 0x7e, 0xc6, 0xc1, 0xd2, 0xf0,
    0xfc, 0xa2, 0x8f, 0x31, 0x3c, 0x1f, 0xf4, 0x00,
    0x79, 0x5e, 0x06, 0xf8, 0x03, 0x29, 0xb0, 0x6e,
    0x37, 0xcc, 0xe6, 0xf3, 0x39, 0xdc, 0xf8, 0x68,
    0xc2, 0x55, 0x32, 0x8d, 0x97, 0xb9, 0x4e, 0x2f,
    0xba, 0x42, 0x24, 0xd3, 0x59, 0x74, 0x07, 0x0f,
    0x36, 0x5c, 0xe6, 0x79, 0x5a, 0xbf, 0xf8, 0x3c,
    0x8c, 0x71, 0x12, 0x4d, 0xb4, 0x05, 0xe7, 0x49,
    0x65, 0x6e, 0x8c, 0x82, 0x69, 0xe3, 0xd9, 0x50,
    0x70, 0xa6, 0x12, 0xf7, 0xb4, 0x40, 0x1f, 0x78,
    0x66, 0x36, 0xcd, 0xcb, 0x09, 0x95, 0xcf, 0x79,
    0xc5, 0xaa, 0xba, 0x63, 0xe0, 0x0c, 0x0c, 0x51,
    0x89, 0x01, 0x90, 0x12, 0x7a, 0x32, 0x6d, 0xd3,
    0xec, 0x71, 0x27, 0xe1, 0x9b, 0x6c, 0x53, 0xb1,
    0x06, 0xbc, 0x0b, 0x4e, 0x22, 0xd8, 0xb7, 0xbc,
    0xbd, 0x12, 0x3a, 0x56, 0xb6, 0x33, 0xb6, 0xa9,
    0x5b, 0x06, 0x66, 0xf2, 0x77, 0x3b, 0x96, 0x0a,
    0x57, 0x73, 0x3d, 0xaf, 0xa7, 0x14, 0x75, 0x1a,
    0x80, 0xf5, 0x2f, 0x1d, 0x46, 0x1d, 0xa8, 0x8a,
    0xb6, 0x70, 0x21, 0x28, 0x0c, 0x78, 0x87, 0xd4,
    0xdc, 0x5c, 0x93, 0x6a, 0x40, 0xca, 0x5c, 0x0d,
    0xb1, 0x42, 0x52, 0x74, 0x09, 0xca, 0xaf, 0x69,
    0x56, 0x07, 0x28, 0xbd, 0x35, 0xdc, 0x54, 0x54,
    0xcc, 0x96, 0x49, 0x8e, 0x1f, 0x8c, 0xf2, 0x9c,
    0x30, 0x83, 0x35, 0xbc, 0x05, 0x93, 0x64, 0xa2,
    0x6d, 0xeb, 0x56, 0xa7, 0xae, 0x76, 0xa1, 0x15,
    0x10, 0x27, 0x55, 0xa7, 0xbb, 0x3b, 0x6f, 0x39,
    0xbc, 0x37, 0x67, 0x5d, 0xcd, 0x34, 0x92, 0x60,
    0xb5, 0xae, 0x01, 0x80, 0xca, 0xd6, 0xf7, 0x15,
    0xf8, 0xa2, 0xcc, 0x99, 0x6d, 0x7f, 0xf8, 0x6e,
    0x0c, 0x05, 0x53, 0x82, 0x79, 0x4b, 0x65, 0xc0,
    0x4a, 0x67, 0xcd, 0x7e, 0x0e, 0xc8, 0xf0, 0x2a,
    0xbc, 0x14, 0x10, 0x89, 0xa9, 0x1c, 0xb3, 0x8b,
    0x65, 0xfd, 0x20, 0xec, 0x6d, 0x18, 0x56, 0xec,
    0xe8, 0xf1, 0x7e, 0xd9, 0xd5, 0xf7, 0xae, 0xa2,
    0xa7, 0x74, 0x77, 0x6f, 0xdd, 0x24, 0x9d, 0xee,
    0x7c, 0x2c, 0xb0, 0x2c, 0x11, 0x08, 0x90, 0x91,
    0xd9, 0x61, 0x39, 0x63, 0x67, 0xb1, 0x10, 0xb7,
    0xb8, 0x12, 0x2d, 0x07, 0xf3, 0x26, 0x57, 0xca,
    0x76, 0xb2, 0x31, 0x8c, 0xf3, 0x64, 0x48, 0x00,
    0x2a, 0xe8, 0x1b, 0xff, 0x26, 0x45, 0xb9, 0x87,
    0xa5, 0x18, 0x64, 0x4b, 0xe1, 0x2e, 0x88, 0x32,
    0xfc, 0x09, 0xed, 0x74, 0x65, 0x05, 0x4a, 0xc5,
    0xfe, 0x95, 0x50, 0x8a, 0x6f, 0x05, 0x83, 0xea,
    0x09, 0x02, 0x9e, 0x55, 0x18, 0x6c, 0x79, 0x25,
    0x15, 0x5a, 0x93, 0x82, 0x74, 0x33, 0xef, 0x0b,
    0x1d, 0x2f, 0x36, 0x0c, 0xf3, 0x03, 0x66, 0x50,
    0x53, 0x1b, 0xbe, 0x78, 0x10, 0xa8, 0x09, 0x4c,
    0x0d, 0xbe, 0xcd, 0xb0, 0xe3, 0x6d, 0xae, 0x8d,
    0xdd, 0x50, 0x63, 0xb9, 0x7f, 0x85, 0xe2, 0xd7,
    0x29, 0x13, 0x83, 0xaf, 0x76, 0x53, 0xd4, 0x8f,
    0x94, 0x73, 0x7d, 0x04, 0x2b, 0xe7, 0x8c, 0x9e,
    0x83, 0xee, 0xa5, 0x51, 0x25, 0x1e, 0x2d, 0x80,
    0xdd, 0xd3, 0x02, 0xa6, 0x0e, 0xe1, 0x82, 0xac,
    0x1a, 0xca, 0x4c, 0xa8, 0xa8, 0xd0, 0x4b, 0x15,
    0xde, 0xd4, 0x4f, 0xc7, 0x1a, 0x5d, 0x9d, 0xf5,
    0x37, 0x6d, 0xbd, 0x05, 0x61, 0x96, 0x70, 0x75,
    0x8e, 0x6f, 0xdb, 0x40, 0x68, 0x87, 0x5b, 0x82,
    0xb0, 0x05, 0x3a, 0x2e, 0x96, 0x00, 0x9f, 0x85,
    0x79, 0x14, 0x1a, 0x2b, 0x7a, 0x16, 0x1c, 0x83,
    0xa2, 0x06, 0x35, 0xa0, 0x25, 0x63, 0x71, 0x73,
    0xe3, 0x08, 0xf6, 0xa4, 0xc3, 0x1e, 0x65, 0x51,
    0x40, 0xb0, 0xca, 0x60, 0xbf, 0x41, 0x83, 0x86,
    0x62, 0xb8, 0xe7, 0x74, 0x12, 0xfa, 0x0e, 0x07,
    0xb6, 0x05, 0x6f, 0xc0, 0x0b, 0x49, 0x87, 0xfa,
    0x02, 0x48, 0x21, 0xcb, 0xbe, 0xb4, 0x73, 0xd6,
    0x39, 0xc0, 0xb2, 0x6e, 0x6c, 0x13, 0x46, 0x17,
    0x6f, 0xb0, 0x99, 0xf6, 0x5b, 0x8d, 0x41, 0x61,
    0xc7, 0xf2, 0xc6, 0x38, 0x72, 0x57, 0xd7, 0x6c,
    0xc3, 0xf5, 0xeb, 0xe8, 0x65, 0x58, 0xab, 0x7e,
    0x09, 0x4d, 0xea, 0x00, 0xde, 0xad, 0x47, 0x24,
    0x28, 0x55, 0xd8, 0x4b, 0x77, 0xa6, 0x28, 0xb6,
    0x7f, 0xd1, 0x22, 0xc3, 0xcd, 0x21, 0x94, 0x2b,
    0xa1, 0xcb, 0xf3, 0xdb, 0x4a, 0xf5, 0x0d, 0x86,
    0x73, 0x41, 0x7e, 0xaf, 0xc1, 0x16, 0xab, 0xa9,
    0xaf, 0xbc, 0xcb, 0x76, 0x79, 0xbd, 0x25, 0x41,
    0xff, 0x40, 0xa5, 0x80, 0xee, 0x10, 0x43, 0xe1,
    0xd3, 0x57, 0xf7, 0xb0, 0x31, 0x82, 0x06, 0x35,
    0x1e, 0x83, 0x79, 0xe5, 0x17, 0xc0, 0x78, 0xc9,
    0x8d, 0x00, 0x55, 0x14, 0x80, 0x21, 0x3a, 0x39,
    0x24, 0x0a, 0x50, 0xc2, 0x2a, 0x32, 0x81, 0xb9,
    0x6f, 0x55, 0x11, 0xa6, 0xd5, 0x55, 0x01, 0x30,
    0xf8, 0x00, 0x1b, 0xf0, 0xbb, 0xc2, 0xa2, 0x9b,
    0x93, 0xd0, 0x5a, 0xd7, 0xae, 0xb6, 0x17, 0x43,
    0x89, 0xe0, 0xa8, 0x58, 0x3e, 0x61, 0x9f, 0x00,
    0x5f, 0x21, 0x46, 0xde, 0x61, 0xca, 0xb1, 0xc1,
    0x66, 0x89, 0xfa, 0x81, 0x4a, 0x33, 0xdd, 0xd4,
    0x76, 0x50, 0x6b, 0x5a, 0xdd, 0x39, 0x75, 0x40,
    0x14, 0x96, 0xbc, 0x15, 0x80, 0x08, 0x59, 0x55,
    0x06, 0xcb, 0xb8, 0x14, 0xbb, 0x14, 0x4b, 0xa3,
    0x8f, 0x16, 0x5d, 0xc1, 0x5b, 0x14, 0x37, 0x16,
    0x32, 0x07, 0x92, 0x17, 0x54, 0x29, 0x39, 0x00,
    0xf6, 0xce, 0x0c, 0x22, 0x93, 0x7b, 0x61, 0xde,
    0x07, 0xd1, 0x6b, 0xaf, 0x1b, 0x84, 0xe1, 0x0b,
    0x32, 0x8c, 0xf9, 0x6c, 0x95, 0x24, 0x3a, 0x1a,
    0x9a, 0xc1, 0x42, 0x87, 0x43, 0x1a, 0x2c, 0x12,
    0x6d, 0x1f, 0x30, 0x58, 0x2c, 0x96, 0xf0, 0x3d,
    0x7f, 0x79, 0xd1, 0x75, 0x4a, 0x03, 0xf0, 0x21,
    0xa8, 0x77, 0x6f, 0xea, 0xe2, 0x30, 0x89, 0x55,
    0x08, 0xaa, 0x55, 0x26, 0x46, 0xd5, 0xf7, 0x31,
    0xda, 0xee, 0xc1, 0x3a, 0xda, 0x97, 0x54, 0xa6,
    0xe6, 0xb3, 0x19, 0x1e, 0x95, 0x23, 0xe1, 0x76,
    0x77, 0xbd, 0xf6, 0x4f, 0xcd, 0xb5, 0x91, 0x9b,
    0x1a, 0xff, 0x16, 0x32, 0xe8, 0xd0, 0x63, 0xdd,
    0xb1, 0x4e, 0xd0, 0x02, 0x4c, 0x3d, 0x3e, 0x68,
    0xbf, 0xd0, 0x8e, 0x87, 0x2a, 0xb8, 0xf5, 0xcc,
    0xff, 0x36, 0x30, 0xe0, 0xe0, 0x41, 0xb1, 0xcd,
    0xf4, 0x8a, 0x79, 0x8e, 0x6e, 0x66, 0xeb, 0x42,
    0xcd, 0xa7, 0xb2, 0x2b, 0x67, 0x59, 0x10, 0x60,
    0x4d, 0xe7, 0x46, 0x3f, 0x50, 0x37, 0x78, 0x70,
    0xce, 0x9a, 0x95, 0x2e, 0x43, 0x00, 0xf9, 0xc2,
    0x7b, 0xaf, 0xf0, 0x07, 0x05, 0xaa, 0xe1, 0xbf,
    0x77, 0x6b, 0xc3, 0x61, 0x3e, 0x52, 0x7f, 0xfa,
    0x31, 0xc6, 0x37, 0xdb, 0x55, 0x53, 0xe0, 0x7f,
    0xae, 0x49, 0xb6, 0x5a, 0xfa, 0xa6, 0xd4, 0x60,
    0xe7, 0x5d, 0x0d, 0x55, 0xf3, 0x76, 0xff, 0x8c,
    0xb0, 0xe7, 0x05, 0xec, 0x6b, 0xdf, 0xe7, 0x49,
    0xad, 0xfe, 0x7d, 0x6a, 0x4d, 0x63, 0x12, 0xcb,
    0x3a, 0xf6, 0xad, 0x9c, 0x80, 0xd4, 0xf5, 0x74,
    0xc8, 0x1e, 0x5e, 0x23, 0x29, 0xd8, 0x5c, 0x20,
    0x10, 0x36, 0xce, 0xaf, 0x8c, 0x4c, 0x80, 0xca,
    0x76, 0x19, 0xfe, 0x8c, 0x91, 0x61, 0x40, 0x3d,
    0xd8, 0x95, 0xf8, 0xbf, 0x8c, 0xac, 0xdf, 0x37,
    0xb2, 0x63, 0x84, 0x36, 0xd7, 0x7a, 0x32, 0xf2,
    0xb6, 0x97, 0xeb, 0xb3, 0x4c, 0xff, 0xb2, 0x90,
    0x21, 0x1d, 0x48, 0x04, 0xa4, 0x10, 0x76, 0x3f,
    0x57, 0x58, 0x9f, 0x7a, 0x6c, 0xb6, 0x8d, 0xa2,
    0xc3, 0x02, 0x98, 0x85, 0x49, 0xec, 0x9f, 0x12,
    0xc1, 0x3a, 0xe4, 0x08, 0x6a, 0xb4, 0x90, 0x01,
    0xfd, 0x71, 0x7a, 0xa8, 0x3c, 0xdf, 0xd3, 0x6f,
    0xd8, 0x6d, 0x09, 0x14, 0x7d, 0x3c, 0x9f, 0x0d,
    0xeb, 0xe1, 0x3f, 0x32, 0x8c, 0x48, 0xa7, 0xd0,
    0x6d, 0xa7, 0x73, 0xda, 0xe5, 0x9a, 0x12, 0x6a,
    0xe5, 0xad, 0x59, 0xf5, 0xa5, 0xf9, 0xa3, 0x7e,
    0x23, 0xa3, 0x8d, 0x7c, 0x85, 0x3b, 0x2a, 0x7f,
    0xa9, 0xb9, 0x07, 0x89, 0xf9, 0xca, 0xd7, 0xb4,
    0xad, 0xc8, 0x04, 0xa0, 0x5e, 0x7e, 0xb8, 0x6e,
    0x3d, 0xc6, 0xec, 0x74, 0x00, 0x82, 0x43, 0x95,
    0x1d, 0x04, 0x86, 0x9e, 0xc2, 0x98, 0xd6, 0xe3,
    0x7a, 0xee, 0x0b, 0xdf, 0xfd, 0x97, 0x62, 0xc9,
    0x4b, 0xc7, 0x24, 0x61, 0x31, 0x1b, 0x14, 0xd3,
    0xdc, 0x95, 0xe7, 0x07, 0x1b, 0xc7, 0x01, 0x88,
    0xac, 0xa7, 0x88, 0xf1, 0x3a, 0xcf, 0xa6, 0xdf,
    0x65, 0xfa, 0x10, 0x61, 0xe6, 0x00, 0xc1, 0xe6,
    0x27, 0x58, 0x28, 0xe7, 0x66, 0xd1, 0x8a, 0x73,
    0x9e, 0x1d, 0xe7, 0xb2, 0xed, 0x9e, 0x8f, 0xa3,
    0x69, 0x14, 0x4d, 0xd7, 0xd1, 0x22, 0x9d, 0xae,
    0x67, 0xd3, 0x64, 0x75, 0xdc, 0x72, 0xd5, 0x40,
    0x44, 0x6a, 0x9f, 0xa1, 0x86, 0x79, 0xf9, 0x2f,
    0x55, 0x6e, 0xf4, 0x92,
};

// Identify size = 2756 (7616 uncompressed)
const uint32_t command_identify_size PROGMEM
    = ARRAY_SIZE(command_identify_data);
